### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by bountyflow** [manwefm/TA-wireguard#1]
My Wireguard server is currently logging Wireguard debug logs to syslog which is then sent to Splunk.
I have installed the TA app but it does not seem to detect the Wireguard logs.

Does this require any additional configuration beyond installing the app and running the `echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control`?

**Comment by ipfyx** [comment]
Hi, 

Do you see your log in any index ?

And how do you send those log to splunk ? Right below is my conf, the logs will be stored under the index "wireguard" using the sourcetype "wireguard:debug".

[monitor:///var/log/wireguard/wg0.log]
disabled = false
index = wireguard
sourcetype = wireguard:debug

**Comment by bountyflow** [comment]
Hi @manwefm,

The logs are stored in syslog by default and Universal Forwarder sends the syslog to Splunk, so I'm seeing the logs in the default index.
However, it seems that I'm missing that sourcetype configuration you provided.
How did you create that wg0.log file since the kernel debug logs go to syslog by default?

**Comment by ipfyx** [comment]
Using rsyslog, i redirect any log matching "wg0:"
$ cat /etc/rsyslog.d/wireguard.conf
:msg,contains,"wg0:" /var/log/wireguard/wg0.log
& stop

This file is included in /etc/rsyslog.conf
$ cat /etc/rsyslog.conf
...
$IncludeConfig /etc/rsyslog.d/*.conf
...

Google is your best friend to find the right config for you ;)

**Comment by bountyflow** [comment]
Ok, works great now.
Thank you!
