### ISSUE TITLE
Syntax errors in props.conf regarding the dvc and name fields

### ISSUE THREAD

**Issue by barrettnet** [manwefm/TA-wireguard#2]
The default/props.conf contains two syntax  errors regarding the dvc and name fields.

The line `EVAL-dvc = interface as dvc` should either be written as `EVAL-dvc = interface` or as `FIELDALIAS-dvc = interface AS dvc`

And likewise for `EVAL-name = interface as name`,it should either be written as `EVAL-name = interface` or as `FIELDALIAS-name = interface AS name`

**Comment by ipfyx** [comment]
Thank you, i fixed it in commit 47f596fd0ec856214183f069d2f555b5334d3d18.
I need to publish the app in splunkbase now.

I am glad somebody is using this app !

**Comment by ipfyx** [comment]
I released v1.1.0 : https://splunkbase.splunk.com/app/5375
